### PR TITLE
fixbug: signed >= unsigned  type error.  

### PR DESCRIPTION
**Pull request by fanlix**
`./match ^1+  abc123` should not match

### CODE REVIEW

**Comment by monolifed** [comment]
`./match ^1+ abc123` 
`type: BEGIN` 
`type: CHAR '1'` 
`type: PLUS` 
`no match` 

This returns "no match". Am I missing something?

**Comment by fanlix** [comment]
Old code works fine for months, untilI I change to a new platform  yesterday .

- arch:  armv71
- os: alpine + glibc
- kernel: 4.19.97
- gcc: 8.3.0

on this platform, tre_match() cause my code into endless loop.
by painful gdb, the problem is here: 
- `while (text - start >= min)`
- condition is true : -2 >= 0

back to x86.debian/centos , the same code runs without error.
some mechanisms prevenct this error. either x86/linux/gcc may have done the job.


the gdb raw data: (can be reproduced on this special platform only)
```
(gdb) n
488             while (text - start >= min)
(gdb) l
483         unsigned min, unsigned max)
484     {
485             const char *end, *start = text;
486             while (max && text < tend && matchone(nodes, *text)) { text++; max--; }
487
488             while (text - start >= min)
489             {
490                     end = matchpattern(nodes + 2, text--, tend);
491                     if (end)
492                             return end;
(gdb) p end
$22 = 0x0
(gdb) p text
$23 = 0x4eeb4f ""
(gdb) p start
$25 = 0x4eeb50 "(123"
(gdb) n
490                     end = matchpattern(nodes + 2, text--, tend);
(gdb) p text
$26 = 0x4eeb4f ""
(gdb) p start
$27 = 0x4eeb50 "(123"
(gdb) n
491                     if (end)
(gdb) n
488             while (text - start >= min)
(gdb) n
490                     end = matchpattern(nodes + 2, text--, tend);
(gdb) p text
$28 = 0x4eeb4e "f"
(gdb) p start
$29 = 0x4eeb50 "(123"
(gdb) p min
$30 = 0
(gdb) p text - start
$31 = -2
(gdb) p text - start >= min
$32 = 1
(gdb) p -2 >= 0
$33 = 0
(gdb) p (text-start) >= min
$34 = 1
(gdb) p text-start >=0
$38 = 0
(gdb) p text-start >= min
$39 = 1
(gdb) p -2 >= min
$40 = 1
(gdb) p -2 >= 0
$41 = 0
```
I guess gcc is the reason.  need more dig later.
- gcc versions 
- compile options
- arch

**anyway, -2  >= unsigned 0  should be avoided.**
and this pr fix the bug.

**Comment by fanlix** [comment]
arm platform, with gcc type warning, result: error-match
```
# uname -a
Linux 8947ca906ef9 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
# gcc --version
gcc (Debian 8.3.0-6) 8.3.0
# make
gcc -O2 -Wall -Wextra -pedantic -std=c99 -o match match.c
In file included from match.c:5:
tre.h:60:3: warning: ISO C99 doesn't support unnamed structs/unions [-Wpedantic]
  };
   ^
In file included from match.c:5:
tre.h: In function 'matchquant':
tre.h:486:22: warning: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Wsign-compare]
  while (text - start >= min)
                      ^~
# ./match ^x?1+  abc123
type: BEGIN
type: CHAR 'x'
type: QMARK
type: CHAR '1'
type: PLUS
match start: 0 match end: 4294967294
```

x86 machine without gcc warning, result: no-match
```
$ uname -a
Linux Win-FX 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
$ make
gcc -O2 -Wall -Wextra -pedantic -std=c99 -o match match.c
In file included from match.c:5:0:
tre.h:60:3: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  };
   ^
$ ./match ^x?1+  abc123
type: BEGIN
type: CHAR 'x'
type: QMARK
type: CHAR '1'
type: PLUS
no match
```

the question is , why second machine success.
`-1>0u`  is always true by my test on both machine.

more dig will be done next week.

**Comment by monolifed** [comment]
Thanks. You are right. It is a problem when min is 0. 
I made some wrong assumptions and gcc didn't warn about it.

**Comment by fanlix** [comment]
# final reason: this is 32bit vs 64bit problem.

## by c standard's **type implicit convertion** rule : 
https://en.cppreference.com/w/c/language/conversion

> 4) Otherwise, both operands are integers. Both operands undergo integer promotions (see below); then, after integer promotion, one of the following cases applies:

1. If the types are the same, that type is the common type.
2. Otherwise (the types are not the same): If the types have the same signedness (both signed or both unsigned), the operand whose type has the lesser conversion rank (see below) is implicitly converted to the other type.
3. Otherwise (the signedness is different): If the unsigned type has conversion rank greater than or equal to the rank of the signed type, then the operand with the signed type is implicitly converted to the unsigned type.
4. Otherwise (the signedness is different, and the unsigned type has conversion rank less than the signed type): If the signed type can represent all values of the unsigned type, then the operand with the unsigned type is implicitly converted to the signed type.
5. Otherwise: Both operands undergo implicit conversion to the unsigned type counterpart of the signed operand's type.

case-4.5 is the problem, this may causes data lost or overflow error


## test code
```
int main() {
        unsigned int u0 = 0;
        int i1 = -1;
        long L1 = -1;

        printf("-1L>0u = %d\n",  L1 > u0);
        printf("-1i>0u = %d\n",  i1 > u0);

        char *p1 = "abc";
        char *p2 = p1 + 1;
        printf("pointer>0u = %d\n",  p1-p2 > u0);

        return 0;
}

```

### on **32bit machine**, pointer type is int32, 
hit case-4.5, -1i converted to unsigned int: 4294967295
causes data overflow error.
```
-1L>0u = 1
-1i>0u = 1
pointer>0u = 1
```
### on **64bit machine**, pointer type is long(int64), 
hit case-4.4, 0u coverted to 0L, everything works fine.
```
-1L>0u = 0
-1i>0u = 1
pointer>0u = 0
```

that's why old buggy code works fine for 99% machines without error.
but explode me 1% 😆 


## gcc warnings
with gcc flag `-Wall -Wextra` there should be 
` warning: comparison between signed and unsigned integer expressions`

but,,, some gcc versions drop this warning. 
maybe they think implicit convertions without data lost is fine.

when changed to 32bit, same convertion may causing problems, they show the warning.

I dont like tools too smart. 😞

**Comment by monolifed** [comment]
Thanks again for the explanation. There doesn't seem to be an option to trigger the warning other than compiling for different targets. I tried `-Wsign-conversion` but it didn't seem to apply in that case.

**Pull request merged**
